config/routes.rb
Rails.application.routes.draw do

  # ============ devise ==============
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # ============ home.controller ==============
  root 'home#index'
  get ":id/enters" => "home#enters"
  get ":post_id/fcshow" => "home#show"
  get ":id/edit_profile" => "home#edit_profile"
  get "account/:id/edit" => "home#edit_account"
  post "user/:id/update" => "home#update_user"
  get "user/:id/fc_list" => "home#fc_list"
  get "others" => "home#others"
  get "policy_law" => "home#policy_law"
  get "home/:id/likes" => "home#likes"
  get "home/new_fc" => "home#new_fc"
  post "home/create" => "home#create"
  get "home/profile/:id" => "home#profile"
  get ":id/show_fc" => "home#show_fc"
  get ":id/edit_fc" => "home#edit_fc"
  post ":id/update_fc" => "home#update_fc"
  post ":id/fc/destroy" => "home#destroy"
  get ":id/setting" => "home#setting"
  get "home/new_fc_content" => "home#new_fc_content"
  post "home/content_create" => "home#content_create"

  # ============ fc_content.controller ==============
  get 'fc_contents/index/:id' => "fc_contents#index"
  get "fc_contents/new/:id" => "fc_contents#new"
  get "fc_content/:id" => "fc_contents#show"
  post "fc_content/create/:id" => "fc_contents#create"


  post "enter/:id/create" => "enters#create"

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  get "pay" => "pay#payment"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only:[:new_fc, :create, :edit_fc, :setting,
                                    :edit_account, :edit_profile]


  def index
    @page_name = "HOME"
    @posts = Post.all.order(created_at: :desc)
    @users = User.all.order(created_at: :desc)
    @likes = Like.where(post_id: params[:post_id])
  end

  def new_fc
    @page_name = "NEW FANCLUB"
  end


  def create
    @post = Post.find_by(id: params[:id])
    @post = Post.new(content: params[:content],
                     user_id: current_user.id,
                     fc_name: params[:fc_name],
                     post_image: "default_post.jpg")

    if @post.save
      # ここから画像保存処理してるんだけどPost.newでpost_iamge: params[:post_image]
      # をしてるからpostテーブルに--.jpgの形で保存されていない。
      if params[:post_image]
        # 画像のリサイズをする

        # アップロードした画像を300x300のサイズに編集
        image = MiniMagick::Image.read(params[:post_image])
        image.resize "200x200"
        @post.post_image = "#{@post.id}.jpg"
        # image = params[:post_image]
        # File.binwrite("public/post_images/#{@post.post_image}",image.read )
        image.write "public/post_images/#{@post.post_image}"
      end
        redirect_to(root_path)
        # flash[:notice] = "ファンクラブを作成しました！これから素晴らしいファンクラブにしていってくださいね♡"
    else
      render("new_fc")

    end
  end


  def show_fc
    @page_name = "ABOUT"
    @post = Post.find_by(id: params[:id])
    @user = @post.user
    @likes_count = Like.where(post_id: @post.id).count
    @member_count = Enter.where(post_id: @post.id).count
  end

  def edit_fc
    @page_name = "EDIT FANCLUB"
    @post = Post.find_by(id: params[:id])
  end

  def update_fc
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    @post.fc_name = params[:fc_name]

    if params[:post_image]
      # @post.post_image = "#{@post.id}.jpg"
      # image = params[:post_image]
      # リサイズしてから保存
      @post.post_image = "#{@post.id}.jpg"
      image = MiniMagick::Image.read(params[:post_image])
      image.resize "200x200"
      image.write "public/post_images/#{@post.post_image}"

      # File.binwrite("public/post_images/#{@post.post_image}",image.read )
    end
    @post.post_image = "#{@post.id}.jpg"

    if @post.save
      flash[:notice] = "編集完了！！！"
      redirect_to("/#{@post.id}/show_fc")
    else
      render("edit_fc")
    end
  end

  def profile
    @page_name = "PROFILE"
    @user = User.find_by(id: params[:id])
    @post = Post.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  def update_user
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    # @user.email = params[:email]
    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.id}.jpg",image.read)
    end
    @user.save
    flash[:notice] = "ユーザー情報を編集しました"
    redirect_to("/home/profile/#{@user.id}")

  end



  def likes
    @user = User.find_by(id: params[:id])
    @post = Post.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to("/")
  end

  def setting
    @page_name = "SETTING"
  end

  def edit_account
    @page_name = "EDIT ACCOUNT"

  end

  def edit_profile
    @page_name = "EDIT PROFILE"

  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  # 加入しているファンクラブ一覧を表示
  def enters
    @user = User.find_by(id: params[:id])
    @enters = Enter.where(user_id: @user.id)
  end

  def fc_list
    @page_name = "LIST"
    @user = User.find_by(id: params[:id])
  end

  def others
  end

  def policy_law
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/edit_account.html.erb
<div class="main edit-account">
  <ul>
    <li><%= link_to "プロフィール編集", "/#{current_user.id}/edit_profile" %></li>
    <li><%= link_to "メールアドレス編集", "/" %></li>
    <li><%= link_to 'パスワード変更', edit_user_registration_path %></li>
    <li><%= link_to "口座情報変更", "/" %></li>
    <li><%= link_to 'ログアウトする', destroy_user_session_path, method: :delete %></li>
  </ul>
</div>

<div class="header-bottom">
  <nav>
    <ul>
      <li>
        <%= link_to ("/") do %>
          <%= image_tag 'home_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
      <li>
        <%= link_to ("/#{current_user.id}/setting") do %>
          <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/home/edit_fc.html.erb
<div class="main">
  <h3 class="title">ファンクラブを編集する</h3>
  <%= form_tag("/#{@post.id}/update_fc", {multipart: true}) do %>
    <input class="btn btn-color-blue btn-size-large" type="submit" value="これで完成！">
    <% @post.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
      <h4 class="about-fc">ファンクラブのヘッダー画像(必須)</h4>
      <!-- fileボタンは装飾が難しいからここは後回し -->
      <input name="post_image" type="file">
      <h4 class="about-fc">ファンクラブ名(必須)</h4>
      <textarea name="fc_name" class="textbox-short"><%= @post.fc_name %></textarea>
      <h4 class="about-fc">ファンクラブの説明(必須)</h4>
      <textarea name="content" class="textbox"><%= @post.content %></textarea>
  <% end %>
</div>

<div class="header-bottom">
  <nav>
    <ul>
      <li>
        <%= link_to ("/") do %>
          <%= image_tag 'home_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
      <li>
        <%= link_to ("/#{current_user.id}/setting") do %>
          <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/home/edit_profile.html.erb
<h3>プロフィール編集</h3>

<%= form_tag("/user/#{current_user.id}/update", {multipart: true}) do %>
  <p>ユーザー名</p>
  <input name="name" class="textbox-short" placeholder="<%= current_user.name %>">
  <input class="btn btn-color-blue btn-size-large" type="submit" value="これで完成！">
<% end %>

<div class="header-bottom">
  <nav>
    <ul>
      <li>
        <%= link_to ("/") do %>
          <%= image_tag 'home_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
      <li>
        <%= link_to ("/#{current_user.id}/setting") do %>
          <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/home/enters.html.erb
<h3 class="">加入しているファンクラブ</h3>
<% @enters.each do |enter|%>
  <% post = Post.find_by(id: enter.post_id)%>
  <%= link_to ("/fc_contents/index/#{post.id}") do %>
    <div class="enter-container">
      <table>
        <tr>
          <td class="">
            <section class="card-enter">
              <div class="card-img-parent">
                <img class="card-img" src="<%= "/post_images/#{post.id}.jpg" %>" alt="">
              </div>
              <div class="card-title">
                <%= link_to(post.fc_name, "/fc_contents/index/#{post.id}") %>
              </div>
            </section>
          </td>
          <td class="enter-fc-content">
            <div class="enter-fc-content">
              <div class=""><%= post.content %></div>
            </div>
          </td>
        </tr>
      </table>
    </div>
  <% end %>
<% end%>

<div class="header-bottom">
  <nav>
    <ul>
      <li>
        <%= link_to ("/") do %>
          <%= image_tag 'home_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>
          <%= link_to ("/#{current_user.id}/setting") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% else %>
          <%= link_to ("/users/sign_in") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/home/fc_list.html.erb
<h3>あなたが作ったファンクラブです</h3>
<% @user.posts.each do |post|%>
  <%= link_to ("/#{post.id}/show_fc") do %>
    <div class="enter-container">
      <table>
        <tr>
          <td class="">
            <section class="card-enter">
              <div class="card-img-parent">
              <% if post.fc_name == "芋あきらの部屋" %>
                <img class="card-img" src="<%= "/post_images/poteto_akira.png" %>" alt="">
              <% else %>
                <img class="card-img" src="<%= "/post_images/#{post.id}.jpg" %>" alt="">
              <% end %>
              </div>
              <div class="card-title">
                <%= link_to(post.fc_name, "/fc_contents/index/#{post.id}") %>
              </div>
            </section>
          </td>
          <td class="enter-fc-content">
            <div class="enter-fc-content">
              <div class=""><%= post.content %></div>
            </div>
          </td>
        </tr>
      </table>
    </div>
  <% end %>
<% end %>

  <div class="header-bottom">
    <nav>
      <ul>
        <li>
          <%= link_to ("/") do %>
            <%= image_tag 'home_aicon.png', :size =>'30x30'%>
          <% end %>
        </li>
        <li>
          <%= link_to ("/#{current_user.id}/setting") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>

app/views/home/index.html.erb
<div class="main">
  <!-- スライダーのcdn -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.min.js"></script>
  <div class="swiper-container">
    <div class="swiper-wrapper">
      <!-- スライダーの速度指定 -->
      <div class="swiper-slide" data-swiper-autoplay="3000">
        <% @posts.each do |post| %>
          <!-- スライダーにリンクをつけている -->
          <% if post.fc_name == "芋あきらの部屋" %>
            <%= link_to ("/#{post.id}/show_fc") do %>
              <%= image_tag("/post_images/poteto_akira.png") %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="swiper-slide" data-swiper-autoplay="3000"><%= image_tag("/post_images/index2.jpg") %></div>
    </div>
    <!-- ページネーション -->
    <div class="swiper-pagination"></div>
  </div>
  <script>
    var mySwiper = new Swiper ('.swiper-container', {
      speed: 1000,
      loop: true,
      autoplay: {
        delay: 1000,
      },
        autoplayDisableOnInteraction:false,
      // ページネーション
      pagination: '.swiper-pagination',
    });
  </script>

<!-- ファンクラブを表示 -->
  <% @posts.each do |post| %>
    <!-- 芋あきらの部屋は運営のファンクラブだから一覧には表示しないようにしている -->
    <% if post.fc_name != "芋あきらの部屋" %>
      <!-- link_to ~ do で画像全体にリンクをかけている -->
      <%= link_to ("/#{post.id}/show_fc") do %>
        <section class="card">
          <!-- 画像のリサイズをする -->
          <div class="card-img-parent">
            <img class="card-img" src="<%= "/post_images/#{post.id}.jpg" %>" alt="">
          </div>
          <div class="card-title">
            <%= link_to(post.fc_name, "/#{post.id}/show_fc") %>
          </div>
        </section>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="header-bottom">
  <nav>
    <ul>
      <li>
        <%= link_to ("/") do %>
          <%= image_tag 'home_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>
          <%= link_to ("/#{current_user.id}/setting") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% else %>
          <%= link_to ("/users/sign_in") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% end %>

      </li>
    </ul>
  </nav>
</div>

app/views/home/likes.html.erb
<!-- <div class="main user-show">
  <div class="container">
    <div class="user">
      <h2><%= @user.name %></h2>

    </div>

    <ul class="user-tabs">
      <li class="active"><%= link_to("#{@user.name}さんがいいねしたファンクラブ", "/home/#{@user.id}/likes") %></li>
    </ul>

    <% @likes.each do |like|%>
      <% post = Post.find_by(id: like.post_id)%>

      <div class="posts-index-item">

        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(@user.name, "/home/profile/#{@user.id}") %>
          </div>
          <%= link_to(@post.content, "/#{post.id}/show_fc") %>
        </div>
      </div>
    <% end%>

  </div>
</div> -->

app/views/home/new_contents.html.erb
<h3>会員特典を自由に決めちゃおう！（他のSNSでは話せない暴露話やオフショット写真など！）</h3>
<%= form_tag("/home/create") do %>
  <textarea name="content"></textarea>
  <input type="submit" value="次へ"></input>
<% end %>

app/views/home/new_fc.html.erb
<%= form_tag("/home/create", {multipart: true}) do %>
  <input class="btn btn-color-blue btn-size-large" type="submit" value="これで完成！">
  <p>ファンクラブのヘッダー画像(必須)</p>
  <!-- fileボタンはcss書くの難しいから保留 -->
  <input name="post_image" type="file">
  <p>ファンクラブ名(必須)</p>
  <textarea class="textbox-short" name="fc_name" type="text" placeholder="ファンクラブ名を入力してね♡"></textarea>
  <p>ファンクラブについて(必須)</p>
  <textarea class="textbox" name="content" type="text" placeholder="ファンクラブについての説明&#13;&#10;
    ・ファンクラブでやっていくこと&#13;&#10;
    例）&#13;&#10;
    ・ファンクラブ会員限定の特別な情報を公開&#13;&#10;
    ・SNSで非公開の絵を毎週公開&#13;&#10;
    ・ライブの情報を先行配信&#13;&#10;
    ・日記を公開&#13;&#10;
    ・会員さんとゆるーくチャット&#13;&#10;"></textarea>
<% end %>

<div class="header-bottom">
  <nav>
    <ul>
      <li>
        <%= link_to ("/") do %>
          <%= image_tag 'home_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
      <li>
        <%= link_to ("/#{current_user.id}/setting") do %>
          <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/home/others.html.erb
<div class="main edit-account">
  <ul>
    <li><%= link_to "特定商取引法に基づく表記", "/policy_law" %></li>
    <li><%= link_to "よくある質問", "#" %></li>
    <li><%= link_to 'お問い合わせ', "#" %></li>
    <li><%= link_to "会員規約", "#" %></li>
    <li><%= link_to 'プライバシーポリシー', "#" %></li>
  </ul>
</div>

app/views/home/policy_law.html.erb
<h2>特定商取引法に基づく表記</h2>

<h3>プロジェクト実行者</h3>

<p>請求がり次第提供致しますので、必要な方は以下プラットフォーマーのお問い合わせ先までご連絡ください。</p>
<h3>運営責任者</h3>

<p>請求がり次第提供致しますので、必要な方は以下プラットフォーマーのお問い合わせ先までご連絡ください。</p>
<h3>住所</h3>

<p>請求がり次第提供致しますので、必要な方は以下プラットフォーマーのお問い合わせ先までご連絡ください。</p>
<h3>電話番号</h3>

<p>請求がり次第提供致しますので、必要な方は以下プラットフォーマーのお問い合わせ先までご連絡ください。</p>
<h3>プラットフォーマー</h3>

<p>こちら（poteto.akira@gmail.com）からお問い合わせください。
※本ファンクラブの取引は、お客様とファンクラブオーナーとの売買契約となり、リターンの配送やコンテンツ等は、ファンクラブオーナーから提供されます。
そのため、お客様・ファンクラブオーナー間のトラブルに関して、本サービス運営者は一切関与せず、責任を負いかねますので、ご了承ください。
（詳細は利用規約をご参照願います）</p>
<h3>お問い合わせ</h3>

<p>ファンクラブオーナーへのお問い合わせは、各ファンクラブページよりおこなってください。</p>
<h3>ファンクラブの会員費</h3>

<p>ファンクラブの会員費は、各ファンクラブページに記載の価格となります。
各ファンクラブページに記載の価格は、全て税込価格です。</p>
<h3>会員費以外の費用</h3>

<p>インターネット接続料金その他の電気通信回線の通信に関する費用は、お客様にて別途ご用意いただく必要があります（金額は、お客様が契約した各事業者が定める通り）。</p>
<h3>支払い方法</h3>

<p>クレジットカード（VISA, Mastercard）でのお支払いとなります。</p>
<h3>支払い期限</h3>

<p>ファンクラブ入会受付完了時に負いて課金され、以降毎月課金が行われます。</p>
<h3>返金等の対応</h3>

<p>入会したファンクラブの会員権の購入のキャンセルは、ファンクラブに明らかな欠陥や問題がある場合を除き、原則受け付けておりません。</p>

<div class="header-bottom">
  <nav>
    <ul>
      <li>
        <%= link_to ("/") do %>
          <%= image_tag 'home_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>
          <%= link_to ("/#{current_user.id}/setting") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% else %>
          <%= link_to ("/users/sign_in") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% end %>

      </li>
    </ul>
  </nav>
</div>

app/views/home/profile.html.erb
  <% if @user.name %>
    <!-- アカウント登録時のユーザー名 -->
    <h2 class="title"><%= @user.name %></h2>
  <% elsif @user.username %>
    <!-- twitterのアカウント名 -->
    <h2 class="title"><%= @user.username %></h2>
  <% end %>

  <div class="profile-image">
    <!-- twitterのアイコン画像を表示 -->
    <% if @user.remote_image_name_url %>
       <%= image_tag(@user.remote_image_name_url) %>
    <% else %>
       <%= image_tag("/user_images/default_image.jpg") %>
    <% end %>
  </div>

<!-- ここからユーザーが作ったファンクラブを表示するエリア =================================-->

  <div class="my-fc">
    <h3 class="who-make-fc"><%= @user.name %>さんが作ったファンクラブ</h3>
    <% @user.posts.each do |post|%>
      <%= link_to ("/#{post.id}/show_fc") do %>
        <div class="enter-container">
          <table>
            <tr>
              <td>
                <section class="card-enter">
                  <div class="card-img-parent">
                    <% if post.fc_name == "芋あきらの部屋" %>
                      <img class="card-img" src="<%= "/post_images/poteto_akira.png" %>" alt="">
                    <% else %>
                      <img class="card-img" src="<%= "/post_images/#{post.id}.jpg" %>" alt="">
                    <% end %>
                  </div>
                  <div class="card-title">
                    <%= link_to(post.fc_name, "/fc_contents/index/#{post.id}") %>
                  </div>
                </section>
              </td>
              <td class="enter-fc-content">
                <div class="enter-fc-content">
                  <div class=""><%= post.content %></div>
                </div>
              </td>
            </tr>
          </table>
        </div>
      <% end %>
    <% end %>
  </div>
<!-- ここまでユーザーが作ったファンクラブを表示するエリア =================================-->

<div class="header-bottom">
  <nav>
    <ul>
      <li>
        <%= link_to ("/") do %>
          <%= image_tag 'home_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>
          <%= link_to ("/#{current_user.id}/setting") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% else %>
          <%= link_to ("/users/sign_in") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/home/setting.html.erb
<div class="main">
  <div class="setting">
    <table class="table-setting">
      <tr>
        <td><%= link_to 'ファンクラブ作成', home_new_fc_path %></td>
        <td><%= link_to 'アカウント編集', "/account/#{current_user.id}/edit" %></td>
        <td></td>
        <!-- <td><%= link_to '加入ファンクラブ', "/#{current_user.id}/enters" %></td> -->
      </tr>
      <tr>
        <td><%= link_to '作成済ファンクラブ', "/user/#{current_user.id}/fc_list" %></td>
        <td><%= link_to 'プロフィール', "/home/profile/#{current_user.id}" %></td>
        <td><%= link_to 'その他', "/others" %></td> <!-- ここに利用規約、個人情報保護方針、特商法に基づく表記、退会とかを書く -->
      </tr>
    </table>
  </div>
  <!-- 入会しているファンクラブがある場合のみ表示 -->
  <% if @enters %>
    <h3 class="">入会しているファンクラブ</h3>
    <% @enters.each do |enter|%>
      <% post = Post.find_by(id: enter.post_id)%>
      <% if post != nil %>
        <%= link_to ("/fc_contents/index/#{post.id}") do %>
      <% else %>
        <div class="enter-container">
          <table>
            <tr>
              <td class="">
                <section class="card-enter">
                  <div class="card-img-parent">
                    <img class="card-img" src="<%= "/post_images/#{post.id}.jpg" %>" alt="">
                  </div>
                  <div class="card-title">
                    <%= link_to(post.fc_name, "/fc_contents/index/#{post.id}") %>
                  </div>
                </section>
              </td>
              <td class="enter-fc-content">
                <div class="enter-fc-content">
                  <div class=""><%= post.content %></div>
                </div>
              </td>
            </tr>
          </table>
        </div>
        <% end %>
      <% end %>
    <% end%>
  <% end %>
</div>

<div class="header-bottom">
  <nav>
    <ul>
      <li>
        <%= link_to ("/") do %>
          <%= image_tag 'home_aicon.png', :size =>'30x30'%>
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>
          <%= link_to ("/#{current_user.id}/setting") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% else %>
          <%= link_to ("/users/sign_in") do %>
            <%= image_tag 'setting_aicon.png', :size =>'30x30'%>
          <% end %>
        <% end %>
      </li>
    </ul>
  </nav>
</div>